//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int UserrID { get; set; }
        public string UserrNameSurname { get; set; }
        public string UserrEmail { get; set; }
        public string UserrPhone { get; set; }
        public string UserrType { get; set; }
        public string Password { get; set; }
    }
}
